### ISSUE TITLE
Feature Request : Dates translation

### ISSUE THREAD

**Issue by ValentinLeTallec** [Souravgoswami/termclock#1]
Hi,
It would be nice if the language for dates could be set through a parameter (or maybe  having it follow the local language setting).

I have seen a few things that suggest that it shouldn't be too hard, but I know nothing of Ruby, so I couldn't figure it out.

- https://guides.rubyonrails.org/i18n.html
- https://stackoverflow.com/questions/6225600/how-do-i-set-up-rails-for-french-language

An example of what I mean would be the clock displaying :
```
12:12:12
Jeudi 12 Décembre 1212
```

**Comment by Souravgoswami** [comment]
Hi, that's a great feature request. We can add translations like:
* Spanish
* Russian
* French
* German
* Italian

Except, we won't be probably touching the time and the ASCII codes we have, adding translation to them will take huge time, and the gem will be way bigger.

We can implement translation but without using gems like i18n or something similar, we will hopefully have an implementation from scratch.

**Comment by Souravgoswami** [comment]
French translations added:

![image](https://user-images.githubusercontent.com/37468605/124378970-092b2f00-dcd2-11eb-86dd-f05cbf8adc8e.png)

The language I understand are Bengali, Hindi, English and Spanish, no idea in french. Would you please like to review the JSON file?

https://github.com/Souravgoswami/termclock/blob/master/lib/translations/fr.json

**Comment by ValentinLeTallec** [comment]
I've made a pull request (#2) with the French json :smile: 
(I didn't close the first '{' because you don't in the original file, but I suppose you should :wink: )

**Comment by Souravgoswami** [comment]
Thanks a lot! BTW, if you take a look carefully, the first brace is closed properly at the end of the file!

**Comment by Souravgoswami** [comment]
Gem version 1.0.0 pushed to rubygems.org:
https://rubygems.org/gems/termclock

You can install it with `gem install termclock`

**Comment by ValentinLeTallec** [comment]
> Thanks a lot! BTW, if you take a look carefully, the first brace is closed properly at the end of the file!

Oh, yes the diff view of git hub confused me :sweat_smile: 

Thanks for the feature :grin:

**Comment by ValentinLeTallec** [comment]
Actually, I just have noticed now while executing it, but we forgot :
Discharging : En décharge 
Charging : En charge
Full : Pleine

Not that it's really important, but I'm telling you for completeness’ sake.

**Comment by Souravgoswami** [comment]
Yup that's true, we forgot about that! Ok, I will add that today or tomorrow...
